services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    init: true
    volumes:
      - ..:/workspaces/tts-server:cached
    command: sleep infinity
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              # Add compute and utility specifically
              capabilities: [gpu, compute, utility]
